apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: outline-deployment
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/nimakaviani/outline-deployment
  secretRef:
    name: outline-deployment
  ref:
    branch: main
